config/routes.rb
Rails.application.routes.draw do
  #updat user settings
  get '/edit', to:'users#edit'
  patch '/edit', to: 'users#update'

  get '/newevent', to: 'events#new'
  post '/newevent', to: 'events#create'
  
  get '/events', to: 'events#index'

  get '/displayevents', to: 'events#display'

  get '/newfromlist', to: 'events#newfromlist'

  root 'welcome#home'

  get '/about', to: 'welcome#about'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #login form
  get '/login', to: 'sessions#new'
  #logging in
  post '/login', to: 'sessions#create'
  #logging out
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	validates :username, :email, :password, #all must be present and < 30 chars
			length: {maximum: 30}, 
			presence: true, on: :create

	validates  :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/,
			message: "email must be of form: example@email.com"},
			uniqueness: true 

	validates :username, format: {with: /\A[a-z0-9\-_]+\Z/,
			message: "may contain letters, numbers, and underscores only"},
			length: {minimum: 3}

	has_secure_password
	validates :password, length: {minimum: 5},
			format: {with: /\A[a-z0-9]+\z/i,
			message: "may contain letters and numbers only, case sensitive"},
			confirmation: true, on: :create
 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#must be logged in to change user settings, working on a seperate page for changing the password
	before_action :authenticate_user, only: [:edit]
	
	def index
	end

	def show
		@user = User.find(params[:id])
		if @user != current_user && check_logged_in
			redirect_to current_user
		elsif @user != current_user
			redirect_to root_url
		end
	end

	def new
		if check_logged_in
			redirect_to current_user
		else 
			@user = User.new
		end
	end
	
	def edit
	end

	def create
		@user = User.new(params.require(:user).permit(:email, :username, :password, :password_confirmation))

		if	@user.save
			session[:user_id] = @user.id
			redirect_to @user
		else
			render 'new'
		end
	end
	def edit
	  @user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

	    if @user.update(params.require(:user).permit(:email, :username, :password)) 
			redirect_to @user
		else 
			render 'edit'
		end
	end

	def destroy
	end


end 

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<body>
<h1>User Settings</h1>


 
<%= form_with model: @user, local: true do |form| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(@user.errors.count, "error")%>  prohibited this message from being saved: 
      </p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<!-- form -->
<div id = "wrap">
  <div id = "outter">
  <p>
    <div class= "t1"><%= form.label :email %></div><br>
    <div class = "email"><%= form.text_field :email %></div>
  </p>

  <p>
    <div class= "t2"><%= form.label :username %></div><br>
    <div class="name"><%= form.text_field :username %></div>
  </p>
 
<!-- working on a seperate page for password change -->



  <p>
    <%= form.submit :id=> "sub"%>
  </p>
  </div>
</div>
 
   <script type="text/javascript">
    var a = [
      "https://upload.wikimedia.org/wikipedia/commons/0/0d/Rakotzbr%C3%BCcke.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Rakotzbr%C3%BCcke.jpg*/,
      "http://www.publicdomainpictures.net/pictures/240000/velka/scenic-landscape-1507476866DSn.jpg"/*Liscenced under Creative Commons - CC0*/,
      "http://www.publicdomainpictures.net/pictures/50000/velka/the-scenic-route.jpg"/*Liscenced under Creative Commons - CC0*/,
      "https://upload.wikimedia.org/wikipedia/commons/3/33/Scenic_View_%40_Park_View_Hotel_%E2%80%93_Hualien%2C_Taiwan_%283981419562%29.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Scenic_View_@_Park_View_Hotel_%E2%80%93_Hualien,_Taiwan_(3981419562).jpg*/
      ]
    document.body.style.backgroundImage = `url(${a[Math.ceil(Math.random()*10000)%a.length]})`;
  </script>

<% end %>
</body>
</html>


app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sign Up</title>
</head>
<body>
<h1>Create new account</h1>


<%= form_with scope: :user, url: users_path, local: true do |form| %>
<!-- show error message -->
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> 
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!-- form -->
<div id = "wrap">
  <div id = "outter">
  <p>
    <div class= "t1"><%= form.label :email %></div><br>
    <div class = "email"><%= form.text_field :email %></div>
  </p>

  <p>
  	<div class= "t2"><%= form.label :username %></div><br>
  	<div class="name"><%= form.text_field :username %></div>
  </p>
 
  <p>
    <div class= "t3"><%= form.label :password %></div><br>
    <div class="password"><%= form.password_field(:password) %></div>
  </p>

  <p>
    <div class= "t4"><%= form.label :password_confirmation, "Confirm password"  %></div><br>
    <div class="confirm"><%= form.password_field(:password_confirmation) %></div>
  </p> 

  <p>
    <%= form.submit :id=> "sub"%>
  </p>
  </div>
</div>

  <script type="text/javascript">
    var a = [
      "https://upload.wikimedia.org/wikipedia/commons/0/0d/Rakotzbr%C3%BCcke.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Rakotzbr%C3%BCcke.jpg*/,
      "http://www.publicdomainpictures.net/pictures/240000/velka/scenic-landscape-1507476866DSn.jpg"/*Liscenced under Creative Commons - CC0*/,
      "http://www.publicdomainpictures.net/pictures/50000/velka/the-scenic-route.jpg"/*Liscenced under Creative Commons - CC0*/,
      "https://upload.wikimedia.org/wikipedia/commons/3/33/Scenic_View_%40_Park_View_Hotel_%E2%80%93_Hualien%2C_Taiwan_%283981419562%29.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Scenic_View_@_Park_View_Hotel_%E2%80%93_Hualien,_Taiwan_(3981419562).jpg*/
      ]
    document.body.style.backgroundImage = `url(${a[Math.ceil(Math.random()*10000)%a.length]})`;
  </script>

<% end %>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= @user.username%>'s profile</title>
	<style type="text/css">
	body{
		background-repeat: no-repeat;
		background-size: cover;
		background-image: url("https://upload.wikimedia.org/wikipedia/commons/5/51/Study_%2816840395246%29.jpg");/*Creative Commons - see https://commons.wikimedia.org/wiki/File:Study_(16840395246).jpg*/
	}
	#welcome{
		background: rgba(255,255,255,0.5);
		width: 500px;
		height: 30px;
		vertical-align: middle;
		text-align: center;
		border-radius: 5px;
		margin-right: auto;
		margin-left: auto;
	}
	#welcomeText{
		width: 500px;
		height: 26px;
		vertical-align: middle;
		text-align: center;
	}
	.banner{
		background: black;
	}
	</style>
</head>
<body>
	<% if @user.created_at.to_date == Date.current %> 
	<header>
		<h1>
			<%= @user.username %>'s homepage <br>
		</h1>
	</header>

	<div id="welcome">
		<table><tr><td id="welcomeText">
		Welcome to AutoCalendar. More stuff will be added here in the future.
		</table></td></tr>
	</div>

	<% else %>
	<header>
		<h1>
			<%= @user.username %>'s homepage <br>
		</h1>

	</header>
	<div id="welcome">
		<table><tr><td id="welcomeText">
		Welcome back. More stuff will be added here in the future.
		</table></td></tr>
	</div>
	
	<% end %>
</body>
</html>

