config/routes.rb
Rails.application.routes.draw do
  #updat user settings
  get '/edit', to:'users#edit'
  patch '/edit', to: 'users#update'

  get '/newevent', to: 'events#new'
  post '/newevent', to: 'events#create'
  
  get '/events', to: 'events#index'

  get '/displayevents', to: 'events#display'

  get '/newfromlist', to: 'events#newfromlist'

  root 'welcome#home'

  get '/about', to: 'welcome#about'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #login form
  get '/login', to: 'sessions#new'
  #logging in
  post '/login', to: 'sessions#create'
  #logging out
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<title>About</title>

<p class="head">Click for Application Mockups:</p>

<br>


<p1 id="events">
	<a href = "https://raw.githubusercontent.com/richardz47/Cmpt-276-Group-Project/v3/app/assets/images/Capture.png">
	Public event 
	</a>
</p1>
<br>
<br>
<p2 id="conversation">
	<a href = "https://raw.githubusercontent.com/richardz47/Cmpt-276-Group-Project/v3/app/assets/images/Capture2.png">
	Chat window  
	</a>
</p2>


<style>

.head{
	font-size: 30px;
	font-family: 'Hind Madurai', sans-serif;
}

#events,#conversation{
	font-family: 'Hind Madurai', sans-serif;
	align-items: center;
	font-size: 30px;

}

#conversation a{
	text-decoration: none;
	align-items: center;
	border: black solid;
	border-radius: 10px;
	text-decoration: none;
	margin-left: 20px;
	color: rgb(0,153,51);

}
#events a{
	align-items: center;
	border: black solid;
	border-radius: 10px;
	text-decoration: none;
	margin-left: 20px;
	color: rgb(0,153,51);
}

app/views/welcome/home.html.erb
<!DOCTYPE html>
<html>
<title>Welcome to the AutoCalendar</title>
<h1>AutoCalendar</h1>

	<body>
		<div class="wrap">
			<div id="arrowL" class="arrow"></div>
			<div id="slider">
				<div class="slide slide1">
					<div class="slideContent">
						<span class="span1">Welcome to AutoCalendar
								
								<% if !(check_logged_in) %>
									<div id = "wrapper_signup">
										<div class = "signup">
											<%= link_to("Sign up", {:controller => 'users',:action => 'new'}) %> 
										<div class = "signup_duo">
											<%= link_to("Sign up", {:controller => 'users',:action => 'new'}) %>
										</div>
										</div>
									</div>


									<div id = "wrapper_login">
										<div class = "login">
											<%= link_to("Log in", {:controller => 'sessions',	:action => 'new'}) %>
										<div class = "login_duo">
											<%= link_to("Log in", {:controller => 'sessions',	:action => 'new'}) %>
										</div>
										</div>>
									</div>


								<% else %>
				
								<% end %>
						</span>
					</div>
				</div>

				<div class="slide slide2">
					<div class="slideContent">
						<span class="span2">Let AutoCalendar Fill Your Schedule</span>
					</div>
				</div>

				<div class="slide slide3">
					<div class="slideContent">
					<div id = "wrapper_Explore">
							<div class = "Explore"><%= link_to "Coming Soon", about_path %>
							<div class = "Explore_duo"><%= link_to "Coming Soon", about_path %>
						</div>
						</div>
					</div>
					</div>
				</div>
			</div>
			<div id="arrowR" class="arrow"></div>
		</div>
		

		<script>
			var sliderImages = document.querySelectorAll('.slide');
			var	arrowR = document.getElementById('arrowR');
			var arrowL = document.getElementById('arrowL');
			var current = 0;
			var pre;
			var after;

			function reset()
			{
				var length = sliderImages.length;
				for(let i=0;i<length; i++)
				{
					sliderImages[i].style.display = 'none';
				}
			}
			function startSlide()
			{
				reset();
				sliderImages[0].style.display = 'block'; 
			}

			function slideLeft(){
				reset();
				sliderImages[current - 1].style.display = 'block';
				current --;
			}
			function slideRight(){
				reset();
				sliderImages[current + 1].style.display = 'block';
				current ++;
			}

			arrowL.addEventListener('click',function(){
				if(current === 0){
					current = sliderImages.length;
					pre = document.getElementByClassName()
				}
				slideLeft();
			})

			arrowR.addEventListener('click',function(){
				if(current === 2){
					current = -1;
				}
				slideRight();
			})
			startSlide();

		</script>





	</body>
</html>