config/routes.rb
Rails.application.routes.draw do
  #updat user settings
  get '/edit', to:'users#edit'
  patch '/edit', to: 'users#update'

  get '/newevent', to: 'events#new'
  post '/newevent', to: 'events#create'
  
  get '/events', to: 'events#index'

  get '/displayevents', to: 'events#display'

  get '/newfromlist', to: 'events#newfromlist'

  root 'welcome#home'

  get '/about', to: 'welcome#about'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #login form
  get '/login', to: 'sessions#new'
  #logging in
  post '/login', to: 'sessions#create'
  #logging out
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    validates :name, :created_by, 
            presence: true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  extend SimpleCalendar
  
  def index
    @events = Event.all
  end
  
  def new
    if check_logged_in
      @event = Event.new
    else 
      redirect_to root_path
    end
  end

  def create
    @event = Event.new(params.require(:event).permit(:name, :start_time, :end_time, :location, :auto, :note))
    @event.created_by = current_user.email

    #Our Geocode API key
    #AIzaSyBLTBPCqHrovJpQ89hsRLf0V6E0zRtW6so
    
    position = @event.location.gsub(' ', '+')
    request = "http://maps.googleapis.com/maps/api/geocode/json?address=" + position
    response = HTTParty.get(request)

    if (response["status"] == "OK")

      x = response["results"][0]["geometry"]["location"]["lat"]
      y = response["results"][0]["geometry"]["location"]["lng"]

      @event.lat = x
      @event.long = y
    end

      if !(@event.end_time > @event.start_time)
        @event.end_time = @event.start_time + 60*30
      end
    @event.duration = ((@event.end_time - @event.start_time) / 60).to_i


    if @event.auto != 'Yes'


      
      respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event added!' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
      end

    else

      @event.end_time = @event.start_time + (@event.duration.to_i * 60)
      

    
      #Our Google direction API key
      #AIzaSyD4UP1Q6w4sV6XDdJgYUbAguPd4YVhPro0

      @events = Event.all

      @events.each do |event|

        pointA = (@event.location).gsub(' ', '+')
        pointB = (event.location).gsub(' ', '+')

        if event.start_time.to_date == Date.current && event.created_by == current_user.email
            if ((event.end_time >= @event.start_time) && (@event.end_time >= event.end_time))
              request = "http://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=" + pointB + "&destinations=" + pointA
              response = HTTParty.get(request)
              if (response["status"] == "OK")
                duration = response["rows"][0]["elements"][0]["duration"]["value"]
              else
                duration = 0
              end

                @event.start_time = event.end_time + 5*60 + duration
                @event.end_time = @event.start_time + (@event.duration.to_i) * 60

            elsif ((event.start_time >= @event.start_time) && (@event.end_time >= event.start_time))

              request = "http://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=" + pointA + "&destinations=" + pointB
              response = HTTParty.get(request)
              if (response["status"] == "OK")
                duration = response["rows"][0]["elements"][0]["duration"]["value"]
              else
                duration = 0
              end

              @event.end_time = event.start_time - 5*60 - duration
              @event.start_time = @event.end_time - (@event.duration.to_i) * 60

            elsif ((event.end_time >= @event.end_time) && (event.start_time <= @event.start_time))
                request = "http://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=" + pointB + "&destinations=" + pointA
                response = HTTParty.get(request)
                if (response["status"] == "OK")
                  duration = response["rows"][0]["elements"][0]["duration"]["value"]
                else
                  duration = 0
                end
  
                  @event.start_time = event.end_time + 5*60 + duration
                  @event.end_time = @event.start_time + (@event.duration.to_i) * 60

            end
        end
      end


      respond_to do |format|    

        if @event.save
          format.html { redirect_to @event, notice: 'Event added!' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
        end

  
    end
  end

  def newfromlist
    if check_logged_in
      @event = Event.new
    else 
      redirect_to root_path
    end
  end

  def edit
    @event = Event.find(params[:id])

    if !((check_logged_in) || (@event.created_by != current_user))
      redirect_to displayevents_path
    end 
  end

  def update
    @event = Event.find(params[:id]) 

    if @event.update(params.require(:event).permit(:name, :start_time, :end_time, :location, :auto, :note))
      @event.update_attributes(duration: (((@event.end_time - @event.start_time) / 60).to_i))

      position = @event.location.gsub(' ', '+')
      request = "http://maps.googleapis.com/maps/api/geocode/json?address=" + position
      response = HTTParty.get(request)
  
      if (response["status"] == "OK")
  
        x = response["results"][0]["geometry"]["location"]["lat"]
        y = response["results"][0]["geometry"]["location"]["lng"]
  
        @event.update_attributes(lat: x, long: y)
      end

      if !(@event.end_time > @event.start_time)
        @event.end_time = @event.start_time + 60*30
      end
      
      if @event.auto == 'Yes'

        @event.update_attributes(end_time: (@event.start_time + (@event.duration.to_i * 60)))

        @events = Event.all

        @events.each do |event|

          if ((event.id != @event.id) && (event.created_by == current_user.email))

          pointA = (@event.location).gsub(' ', '+')
          pointB = (event.location).gsub(' ', '+')

          if event.start_time.to_date == Date.current && event.created_by == current_user.email
            if ((event.end_time >= @event.start_time) && (@event.end_time >= event.end_time))
              request = "http://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=" + pointB + "&destinations=" + pointA
              response = HTTParty.get(request)
              if (response["status"] == "OK")
                duration = response["rows"][0]["elements"][0]["duration"]["value"]
              else
                duration = 0
              end

                @event.update_attributes(start_time: (@event.start_time = event.end_time + 5*60 + duration))
                @event.update_attributes(end_time: (@event.start_time + (@event.duration.to_i) * 60))

            elsif ((event.start_time >= @event.start_time) && (@event.end_time >= event.start_time))

              request = "http://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=" + pointA + "&destinations=" + pointB
              response = HTTParty.get(request)
              if (response["status"] == "OK")
                duration = response["rows"][0]["elements"][0]["duration"]["value"]
              else
                duration = 0
              end

              @event.update_attributes(end_time: (event.start_time - 5*60 - duration))
              @event.update_attributes(start_time: (@event.end_time - (@event.duration.to_i) * 60))

            elsif ((event.end_time >= @event.end_time) && (event.start_time <= @event.start_time))
              request = "http://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins=" + pointB + "&destinations=" + pointA
              response = HTTParty.get(request)
              if (response["status"] == "OK")
                duration = response["rows"][0]["elements"][0]["duration"]["value"]
              else
                duration = 0
              end

              @event.update_attributes(start_time: (@event.start_time = event.end_time + 5*60 + duration))
              @event.update_attributes(end_time: (@event.start_time + (@event.duration.to_i) * 60))

            end
        end        

      end
        
        end

      end

        redirect_to @event
    else
      render 'edit'
    end
  end

  def display
    if !check_logged_in
      redirect_to root_path
    else
      @events = Event.all 
    end
  end

  def show
    @event = Event.find(params[:id])
    if check_logged_in
      if @event.created_by != current_user.email
        redirect_to displayevents_path
      end
    else
      redirect_to root_path
    end
  end
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
   
    redirect_to displayevents_path
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/display.html.erb
<title>My Calendar</title>
<h1>Calendar</h1>
<style>
#outercalendar{
  width: 50%;
  height: 100%;
}
#map{
  width: 50%;
  height: 100%;
  float: right;
}
#eventdesc{
  width: 40%
}
</style>

<div id="map"></div>

<script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 49.252612, lng: -123.122183},
      zoom: 12
    });
    navigator.geolocation.getCurrentPosition(function(position){
      if(navigator.geolocation){
        map.panTo({lat: position.coords.latitude ,lng: position.coords.longitude});
      }
    });
    google.maps.event.addListenerOnce(map, 'idle', function(){
      // do something only the first time the map is loaded
      console.log("Map ready");
      <% @events.each do |event| %>

      <% if (event.lat != nil && event.long != nil) && (event.start_time.to_date == Date.current) && (event.created_by == current_user.email) %>

        var info = '<h3><%= link_to event.name, event %></h3>' + '<p>Location: <%= event.location%></p>' + 
                    '<p>Start: <%= (event.start_time).strftime("%I:%M%p") %></p>' + '<p>End: <%= event.end_time.strftime("%I:%M%p") %></p>';
        console.log(`lat:`,<%= event.lat %>, `lng:`, <%= event.long %>);
        addMarker({lat:<%= event.lat %>, lng:<%= event.long %>}, info);
      <% end %>
      <% end %>
    });
  }

  function addMarker(coords, info){

    var geocoder = new google.maps.Geocoder;

    var infowindow = new google.maps.InfoWindow({
      content: ''
    });

    geocoder.geocode({'location': coords}, function(results, status) {
      if (status === 'OK') {
        if (results[0]) {
          infowindow.setContent(info);
        }
      }
    });

    var marker = new google.maps.Marker({
      position: coords,
      map: map,
      label: location[0],

    });
    marker.addListener('click',function(){infowindow.open(map, marker)});
  }  
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDWTEfQsPN2d_kg8ST-ReFixdVCCIJrrlI&callback=initMap" ></script>

<div id="outercalendar">
<table id='eventdesc'>
  <tr>
    <th>Name</th>
    <th>From</th> 
    <th>To</th>
    <th>Location</th>
  </tr>

  <% @events.sort_by{|event| event.start_time.strftime('%H:%M')}.each do |event| %>

  
  <% if event.start_time.to_date == Date.current %>
  <% if event.created_by == current_user.email %>

  <tr>
    <td><%= link_to event.name, event %></td>
    <td><%= (event.start_time).strftime("%I:%M%p") %></td> 
    <td><%= event.end_time.strftime("%I:%M%p") %></td>
    <td><%= event.location %></td>
    <td><%= link_to 'Delete', event_path(event),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
  </tr>
  <% end %>
  <% end %>
  <% end %>

</table>

<br>
<%= link_to("Add event", {:controller => 'events',:action => 'new'}) %>
<br>
<%= link_to("Add event from list", {:controller => 'events',:action => 'newfromlist'}) %>
<br>

<%= month_calendar events: @events do |date, events| %>
  <%= date.day %>

  <% events.each do |event| %>
    <% if event.created_by == current_user.email %>
    <div>
      <%= link_to event.name, event %>
    </div>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/events/edit.html.erb
<!DOCTYPE html>
<html>
<title>Edit event</title>
<body>
<h1>Edit event</h1>


<%= form_with model: @event do |form| %>
<!-- show error message -->	
<% if @event.errors.any? %>
    <div id="error_explanation">
      <h>
        <%= pluralize(@event.errors.count, "error") %> 
      </h>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!-- form -->
<div id = "wrap">
  <div id = "outter">
  <p>
    <div class= "t1"><%= form.label :name %></div><br>
    <div class = "name"><%= form.text_field :name %></div>
  </p>

  <p>
  	<div class= "t2"><%= form.label :start_time %></div><br>
  	<div class= "start"><%= form.datetime_select :start_time %></div>
  </p>
 
 <p>
    <div class= "t3"><%= form.label :end_time %></div><br>
    <div class="end"><%= form.datetime_select :end_time  %></div>
  </p>

  <p>
  <div class= "t4"><%= form.label :location %></div><br>
  <div class="location"><%= form.text_field :location  %></div>
  </p>

  <p>
  <div class= "t5"><%= form.label :auto %></div><br>
  <div class="choice"><%= form.select :auto, ['Yes', 'No']  %></div>
  </p>

  <p>
  <div class= "t6"><%= form.label :note %></div><br>
  <div class="notes"><%= form.text_area :note %></div>
  </p>

  <p>
    <%= form.submit "Update",:id=> "sub"%>
  </p>
  </div>
</div>

  <script type="text/javascript">
    var a = [
      "https://upload.wikimedia.org/wikipedia/commons/0/0d/Rakotzbr%C3%BCcke.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Rakotzbr%C3%BCcke.jpg*/,
      "http://www.publicdomainpictures.net/pictures/240000/velka/scenic-landscape-1507476866DSn.jpg"/*Liscenced under Creative Commons - CC0*/,
      "http://www.publicdomainpictures.net/pictures/50000/velka/the-scenic-route.jpg"/*Liscenced under Creative Commons - CC0*/,
      "https://upload.wikimedia.org/wikipedia/commons/3/33/Scenic_View_%40_Park_View_Hotel_%E2%80%93_Hualien%2C_Taiwan_%283981419562%29.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Scenic_View_@_Park_View_Hotel_%E2%80%93_Hualien,_Taiwan_(3981419562).jpg*/
      ]
    document.body.style.backgroundImage = `url(${a[Math.ceil(Math.random()*10000)%a.length]})`;
  </script>

<% end %>
</body>
</html>

app/views/events/index.html.erb
<h1>Listing events</h1>
 
<table>
  <tr>
    <th>Name</th>
  </tr>
 
  <% @event.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= link_to 'Destroy', event_path(event),
        	method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
     <%= link_to("Edit", {:controller => 'events',:action => 'edit'}) %>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
<title>New event</title>
<body>
<h1>Add new event</h1>


<%= form_with model: @event do |form| %>
<!-- show error message -->	
<% if @event.errors.any? %>
    <div id="error_explanation">
      <h>
        <%= pluralize(@event.errors.count, "error") %> 
      </h>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!-- form -->
<div id = "wrap">
  <div id = "outter">
  <p>
    <div class= "t1"><%= form.label :name %></div><br>
    <div class = "name"><%= form.text_field :name %></div>
  </p>

  <p>
  	<div class= "t2"><%= form.label :start_time %></div><br>
  	<div class= "start"><%= form.datetime_select :start_time %></div>
  </p>
 
 <p>
    <div class= "t3"><%= form.label :end_time %></div><br>
    <div class="end"><%= form.datetime_select :end_time  %></div>
  </p>

  <p>
  <div class= "t4"><%= form.label :location %></div><br>
  <div class="location"><%= form.text_field :location  %></div>
  </p>

  <p>
  <div class= "t5"><%= form.label :auto %></div><br>
  <div class="choice"><%= form.select :auto, ['No', 'Yes']  %></div>
  </p>

  <p>
  <div class= "t6"><%= form.label :note %></div><br>
  <div class="notes"><%= form.text_area :note %></div>
  </p>

  <p>
    <%= form.submit "Add Event",:id=> "sub"%>
  </p>
  </div>
</div>

  <script type="text/javascript">
    var a = [
      "https://upload.wikimedia.org/wikipedia/commons/0/0d/Rakotzbr%C3%BCcke.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Rakotzbr%C3%BCcke.jpg*/,
      "http://www.publicdomainpictures.net/pictures/240000/velka/scenic-landscape-1507476866DSn.jpg"/*Liscenced under Creative Commons - CC0*/,
      "http://www.publicdomainpictures.net/pictures/50000/velka/the-scenic-route.jpg"/*Liscenced under Creative Commons - CC0*/,
      "https://upload.wikimedia.org/wikipedia/commons/3/33/Scenic_View_%40_Park_View_Hotel_%E2%80%93_Hualien%2C_Taiwan_%283981419562%29.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Scenic_View_@_Park_View_Hotel_%E2%80%93_Hualien,_Taiwan_(3981419562).jpg*/
      ]
    document.body.style.backgroundImage = `url(${a[Math.ceil(Math.random()*10000)%a.length]})`;
  </script>

<% end %>
</body>
</html>

app/views/events/newfromlist.html.erb
<!DOCTYPE html>
<html>
<title>New event</title>
<body>
<h1>Preset Events</h1>


<%= form_with model: @event do |form| %>
<!-- show error message -->	
<% if @event.errors.any? %>
    <div id="error_explanation">
      <h>
        <%= pluralize(@event.errors.count, "error") %> 
      </h>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<!-- form -->
<div id = "wrap">
  <div id = "outter">
  <p>
    <div class= "t1"><%= form.label :name %></div><br>
    <div class = "name"><%= form.select :name, ["task1", "task2", "task3", "task4"] , :include_blank => '-select-'%></div>
  </p>

  <p>
  	<div class= "t2"><%= form.label :start_time %></div><br>
  	<div class= "start"><%= form.datetime_select :start_time %></div>
  </p>
   <p>
    <div class= "t3"><%= form.label :end_time %></div><br>
    <div class= "t6"><%= form.label :duration, "default duration is 30 minutes" %></div><br>
    <div class="end"><%= form.datetime_select :end_time  %></div>
  </p>


  <p>
  <div class= "t4"><%= form.label :location %></div><br>
  <div class="location"><%= form.text_field :location  %></div>
  </p>

  <p>
  <div class= "t5"><%= form.label :auto %></div><br>
  <div class="choice"><%= form.select :auto, ['Yes']  %></div>
  </p>


  <p>
    <%= form.submit "Add Event",:id=> "sub"%>
  </p>
  </div>
</div>

  <script type="text/javascript">
    var a = [
      "https://upload.wikimedia.org/wikipedia/commons/0/0d/Rakotzbr%C3%BCcke.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Rakotzbr%C3%BCcke.jpg*/,
      "http://www.publicdomainpictures.net/pictures/240000/velka/scenic-landscape-1507476866DSn.jpg"/*Liscenced under Creative Commons - CC0*/,
      "http://www.publicdomainpictures.net/pictures/50000/velka/the-scenic-route.jpg"/*Liscenced under Creative Commons - CC0*/,
      "https://upload.wikimedia.org/wikipedia/commons/3/33/Scenic_View_%40_Park_View_Hotel_%E2%80%93_Hualien%2C_Taiwan_%283981419562%29.jpg"/*Liscenced under Creative Commons - see https://commons.wikimedia.org/wiki/File:Scenic_View_@_Park_View_Hotel_%E2%80%93_Hualien,_Taiwan_(3981419562).jpg*/
      ]
    document.body.style.backgroundImage = `url(${a[Math.ceil(Math.random()*10000)%a.length]})`;
  </script>

<% end %>
</body>
</html>

app/views/events/show.html.erb
<title><%= @event.name %></title>

<h1><%= @event.name %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time.to_date %>
  <%= (@event.start_time).strftime("%I:%M%p") %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time.to_date %>
  <%= (@event.end_time).strftime("%I:%M%p") %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @event.note %>
</p>

<td><%= link_to 'Delete', event_path(@event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
   <%= link_to("Edit", {:controller => 'events',:action => 'edit'}) %>


<%= link_to "Back", displayevents_path %>