config/routes.rb
Rails.application.routes.draw do
  #updat user settings
  get '/edit', to:'users#edit'
  patch '/edit', to: 'users#update'

  get '/newevent', to: 'events#new'
  post '/newevent', to: 'events#create'
  
  get '/events', to: 'events#index'

  get '/displayevents', to: 'events#display'

  get '/newfromlist', to: 'events#newfromlist'

  root 'welcome#home'

  get '/about', to: 'welcome#about'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  #login form
  get '/login', to: 'sessions#new'
  #logging in
  post '/login', to: 'sessions#create'
  #logging out
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
      .calendar-heading{
        text-align: center;
        height: 40px;
      }
      .calendar-heading > a{
        padding: 5px 5px 5px 5px;
        border-radius: 5px;
        color: black;
        font-size: 20px;
        text-decoration: none;
        background-color: rgba(200,200,200,0.8);
        font-family: Arial, Helvetica, sans-serif;
      }
      .calendar-heading > span{
        padding: 5px 5px 5px 5px;
        color: black;
        font-size: 25px;
        text-decoration: none;
        font-family: Arial, Helvetica, sans-serif;
      }
    
    </style>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="banner">
      <%= link_to image_tag("IMG_2634.JPG", border: 5, width:55, height:55), root_path, id: "logo" %>
      <% if check_logged_in %>
        <%= link_to "My Calendar", displayevents_path %>
        <%= link_to "My Profile", current_user %>
        <%= link_to "Settings", edit_user_path(current_user) %>
        <%= link_to "Log Out", logout_path, method: :delete, id: "logOut" %>
      <% end %>
    </div>

      <%= yield %>
  </body>
</html>